version: "3.7"
services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.6
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mg_data/mongo1:/data/db
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "ca",
        "--bind_ip",
        "0.0.0.0",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    depends_on:
      - mongo2
      - mongo3
    networks:
      - mongo-network

  mongo2:
    container_name: mongo2
    image: mongo:4.4.6
    ports:
      - 27018:27017
    restart: always
    volumes:
      - ./mg_data/mongo2:/data/db
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "ca",
        "--bind_ip",
        "0.0.0.0",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    networks:
      - mongo-network

  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.4.6
    ports:
      - 27019:27017
    restart: always
    volumes:
      - ./mg_data/mongo3:/data/db
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "ca",
        "--bind_ip",
        "0.0.0.0",
        "--wiredTigerCacheSizeGB",
        "1",
      ]
    networks:
      - mongo-network

  setup_rs:
    image: mongo:4.4.6
    volumes:
      - ./setup.sh:/setup.sh
    environment:
      - MONGO1=mongo1
      - MONGO2=mongo2
      - MONGO3=mongo3
    entrypoint: ["/setup.sh"]
    depends_on:
      - mongo1
    networks:
      - mongo-network

networks:
  mongo-network:
    name: mongo-network
